from selenium.webdriver.common.by import By


class Locators:
    COOKIE_BUTTON = (By.XPATH, '//button[@class = "App_CookieButton__3cvqF"]')
    ACCORDION = (By.CLASS_NAME, 'accordion')
    ONE_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-0"]/parent::div[@class = "accordion__heading"]')
    ONE_ANSWER = (By.XPATH, '//p[contains(text(), "Сутки — 400 рублей. Оплата курьеру — наличными или картой.")]')
    TWO_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-1"]/parent::div[@class = "accordion__heading"]')
    TWO_ANSWER = (By.XPATH, '//p[contains(text(), "Пока что у нас так: один заказ — один самокат. Если хотите покататься с друзьями, можете просто сделать несколько заказов — один за другим.")]')
    THREE_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-2"]/parent::div[@class = "accordion__heading"]')
    THREE_ANSWER = (By.XPATH, '//p[contains(text(), "Допустим, вы оформляете заказ на 8 мая. Мы привозим самокат 8 мая в течение дня. Отсчёт времени аренды начинается с момента, когда вы оплатите заказ курьеру. Если мы привезли самокат 8 мая в 20:30, суточная аренда закончится 9 мая в 20:30.")]')
    FOUR_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-3"]/parent::div[@class = "accordion__heading"]')
    FOUR_ANSWER = (By.XPATH, '//p[contains(text(), "Только начиная с завтрашнего дня. Но скоро станем расторопнее.")]')
    FIVE_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-4"]/parent::div[@class = "accordion__heading"]')
    FIVE_ANSWER = (By.XPATH, '//p[contains(text(), "Пока что нет! Но если что-то срочное — всегда можно позвонить в поддержку по красивому номеру 1010.")]')
    SIX_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-5"]/parent::div[@class = "accordion__heading"]')
    SIX_ANSWER = (By.XPATH, '//p[contains(text(), "Самокат приезжает к вам с полной зарядкой. Этого хватает на восемь суток — даже если будете кататься без передышек и во сне. Зарядка не понадобится.")]')
    SEVEN_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-6"]/parent::div[@class = "accordion__heading"]')
    SEVEN_ANSWER = (By.XPATH, '//p[contains(text(), "Да, пока самокат не привезли. Штрафа не будет, объяснительной записки тоже не попросим. Все же свои.")]')
    EIGHT_QUESTION = (By.XPATH, '//div[@id= "accordion__heading-7"]/parent::div[@class = "accordion__heading"]')
    EIGHT_ANSWER = (By.XPATH, '//p[contains(text(), "Да, обязательно. Всем самокатов! И Москве, и Московской области.")]')
    BUTTON_ORDER_UP = (By.CLASS_NAME, 'Button_Button__ra12g')
    BUTTON_ORDER_DOWN = (By.XPATH, '//button[@class = "Button_Button__ra12g Button_Middle__1CSJM"]')
    FIELD_NAME = (By.XPATH, '//input[@placeholder = "* Имя"]')
    FIELD_LAST_NAME = (By.XPATH, '//input[@placeholder = "* Фамилия"]')
    FIELD_ADDRESS = (By.XPATH, '//input[@placeholder = "* Адрес: куда привезти заказ"]')
    FIELD_METRO = (By.CLASS_NAME, "select-search__input")
    METRO_NAME_ONE =  (By.XPATH, './/*[text() = "Черкизовская"]')
    FIELD_PHONE = (By.XPATH, '//input[@placeholder = "* Телефон: на него позвонит курьер"]')
    FIELD_DATA = (By.XPATH, '//input[@placeholder = "* Когда привезти самокат"]')
    FIELD_TERM = (By.XPATH, "//div[@class = 'Dropdown-root']")
    TERM_ONE_DAY = (By.XPATH, '//div[contains(text(), "сутки")]')
    BUTTON_ORDER = (By.XPATH, '//div[@class = "Order_Buttons__1xGrp"]/button[contains(text(), "Заказать")]')
    BUTTON_NEXT = (By.XPATH, "//button [@class = 'Button_Button__ra12g Button_Middle__1CSJM']")
    BUTTON_LOGO = (By.CLASS_NAME, "Header_LogoScooter__3lsAR")
    BUTTON_YA = (By.XPATH, "//a[@class = 'Header_LogoYandex__3TSOI']")
    BUTTON_YES = (By.XPATH, '//button[contains(text(), "Да")]')
    ORDER_TEXT_SUCCESS = (By.XPATH, '//button[contains(text(), "Посмотреть статус")]')
    CALENDAR_DATE = (By.XPATH, '//div[@class = "react-datepicker__day react-datepicker__day--001 react-datepicker__day--selected"]')

